### ISSUE TITLE
Best strategy for exposing Tone audio node attributes as widgets on the backend side

### ISSUE THREAD

**Issue by benbovy** [benbovy/ipytone#18]
Taking [Oscillator](https://github.com/benbovy/ipytone/blob/e87ac10c8c1f65ee9ddb02c3a0a141cdc36d8468/ipytone/source.py#L37) as an example: in javascript, `Tone.Oscillator` has two read-only attributes, `frequency` and `detune`, which are `Tone.Signal` instances.

We want to be able handling these attributes from Python, e.g., connect other nodes (widgets) to the input of the oscillator's `frequency` and `detune` signal nodes. Since `ipytone` provides a [Signal](https://github.com/benbovy/ipytone/blob/e87ac10c8c1f65ee9ddb02c3a0a141cdc36d8468/ipytone/signal.py#L69) widget class, best would be that 

```python
osc = ipytone.Oscillator()
isinstance(osc.frequency, ipytone.Signal)   # True
isinstance(osc.detune, ipytone.Signal)   # True
````

Ideally, we would need to create two `SignalModel` instances when initializing the `OscillatorModel` instance in javascript. But apparently (sadly) it's not possible to create new (synchronized) widget instances from Javascript (see https://github.com/jupyter-widgets/ipywidgets/issues/911).

The current workaround is to create two separate `Signal` objects on the Python side when creating a new `Oscillator` object, which are then connected internally to the `Tone.Oscillator` object's `frequency` and `detune` nodes and which are exposed as read-only properties in the `Oscillator` Python class. While this approach works, it may result in a lot of unnecessary duplicate audio nodes in javascript. This oscillator example is also quite simple and this approach may not be easily applied in more complex situations, e.g., wrapping in `ipytone` some Tone synthesizers with lots of nodes (signals, envelopes, etc.).

pin @davidbrochart @martinrenou in case you know better workarounds.

**Comment by martinRenou** [comment]
> (see jupyter-widgets/ipywidgets#911).

This might have been my first issue ever on Github! ahah

This is actually possible, I recall bqplot does instantiate widgets from the front-end. Here: https://github.com/bqplot/bqplot/blob/958b0679cbccbc1411688cc6f8a5a22642377c68/js/src/Toolbar.ts#L114.

When you get the result `SignalModel` you might be able to set it with `this.set('frequency', signal_model)`, `this` being your `OscillatorModel`.

**Comment by benbovy** [comment]
Ah very good to know! Thanks for the pointer @martinRenou !

In the meantime I found a solution to avoid duplicating audio nodes with the workaround described above (just replace the `SignalModel.node` attribute by the Tone oscillator's node, instead of connecting them together), but creating the models from the front-end may be cleaner.

> This might have been my first issue ever on Github! ahah

Ah yes I saw that it's quite old :)

**Comment by benbovy** [comment]
Hmm I haven't figured out how to serialize the new `SignalModel` set as the oscillator's `frequency`, as in Python I get something like `'IPY_MODEL_8b1736d7-40cc-4bcb-b1d2-c7bbd0a2b076'`. It's weird because in `OscillatorModel` I have defined:

```typescript
// note: I haven't seen any serialize function registered for '_panzoom' in the bqplot example

static serializers: ISerializers = {
    ...SourceModel.serializers,
    frequency: { deserialize: unpack_models as any }, 
  };
```

and in Python

```python
frequency = Instance(
    Signal, read_only=True, default_value=None, allow_none=True
).tag(sync=True, **widget_serialization);
```

Also, I'm wondering if it's ok to provide empty strings for the `view_<...>` options to `widget_manager.new_widget` (since there's no view here) and how (if possible) to use `SignalModel`'s custom methods for the new created model, e.g.,

```typescript
  // set Promise<SignalModel> as return type gives typescript error like
  // "Type 'WidgetModel' is missing the following properties ..." (defined in SignalModel)
  createNewModel() : Promise<WidgetModel> {     
    return this.widget_manager.new_widget({
      model_name: 'SignalModel',
      model_module: this.get('_model_module'),
      model_module_version: this.get("_model_module_version"),
      view_name: '',
      view_module: '',
      view_module_version: '',
    }).then(function(model) {
      model.some_signal_model_method();     // does not exist on WidgetModel

      model.save_changes();
      return model;
    });

```

**Comment by martinRenou** [comment]
> Hmm I haven't figured out how to serialize the new SignalModel set as the oscillator's frequency, as in Python I get something like 'IPY_MODEL_8b1736d7-40cc-4bcb-b1d2-c7bbd0a2b076'. It's weird because in OscillatorModel I have defined:

Right. I don't know actually. You are only setting a `deserialize` but not a `serialize` one, but I am not sure what should be set for the serializer. We should maybe look into the ipywidgets codebase, I guess around where `unpack_models` is defined there might be a function that does the opposite. If we are lucky there might be a `pack_models` one ahah.

> Also, I'm wondering if it's ok to provide empty strings for the view_<...> options to widget_manager.new_widget (since there's no view here) and how (if possible) to use SignalModel's custom methods for the new created model, e.g.,

I guess it's fine to not even set them?

**Comment by benbovy** [comment]
>  If we are lucky there might be a pack_models

There [used to be one](https://github.com/jupyter-widgets/ipywidgets/blob/86a894132c933fd1103669c5bcea2d1630749e82/IPython/html/static/widgets/js/widget.js#L226) but [I don't see it anymore](https://github.com/jupyter-widgets/ipywidgets/blob/51322341d4f6d88449f9dbf6d538c60de6d23543/packages/base/src/widget.ts#L31)

> I guess it's fine to not even set them?

It seems it is [still required](https://github.com/jupyter-widgets/ipywidgets/blob/51322341d4f6d88449f9dbf6d538c60de6d23543/packages/base-manager/src/manager-base.ts#L191) 

I'll investigate a bit further to see if I can get it working, otherwise I'll stick with creating the widgets from within Python for now. Thanks for your help so far @martinRenou !

**Comment by martinRenou** [comment]
You might be able to implement your own serializer by defining a function that returns `'IPY_MODEL_' + model.model_id`, I am not sure if that works though, it might be worth giving it a try.

**Comment by benbovy** [comment]
Ok it mostly works!

It turns out it wasn't necessary to add a serializer, but it was necessary to register the widget like this:

```python
ipywidgets.Widget.widget_types.register("ipytone", "^0.2.0", "SignalModel", "", "", "", ipytone.Signal)
```

I wonder if that's because of the empty strings for the view options (we can't use `null` for those options in `widget_manager.new_widget`). One thing slightly annoying: the repr of the signal widget tries to show a view in the notebook, which doesn't exists (whereas I want to show to model repr).

**Comment by benbovy** [comment]
The issue I have now is that the widgets created asynchronously on the front-end side are not directly available in Python, i.e.,

```python
In [1]: osc = ipytone.Oscillator()
   ...: osc.frequency      # returns None (not available yet)

In [2]: osc.frequency
Out[2]: Signal(frequency=440.0, units='frequency')
```

Unfortunately I don't think it's possible to trigger the creation of a widget from JS and access it from Python within the same notebook code cell (unless using async/await, but that would be too complicated), but I'd be happy to be wrong.

**Comment by davidbrochart** [comment]
Maybe you can `observe` the `frequency` and get notified when it's created?

**Comment by davidbrochart** [comment]
Also, I recently started https://github.com/davidbrochart/attrait, you could copy/paste the code that allows you to:
```python
await change(frequency)
```
In the Notebook you can directly use `await` without worrying about the event loop.

**Comment by benbovy** [comment]
Thanks @davidbrochart. I've tried using attrait (which looks very handy), but for some reason it blocks forever even if I see in the JS console the value being changed (I might be doing something wrong, though). `observe` works fine, although I have to block for a little while in JS to avoid the widget be fully initialized before Python is listening for changes).

Thinking more about it, I'm not sure if going asynchronous is worth the trouble here, but I'm not sure either how we can really avoid it if we want fine grained control over Tone audio nodes (unless re-implementing a lot of Tone in Python), so I'm not sure what to do now.

**Comment by davidbrochart** [comment]
Sorry, `await` can't be used here since the Python interpreter has to be idle for the front-end to execute the `frequency` value change in the back-end. So you're pretty much left with registering a callback with `observe`, but then the notebook looses its linearity and interactivity...
Something I was thinking about, what if an `ipytone.Signal` had a default value other than `None`, which would represent an "uninstanciated" `Tone.Signal`? When it is affected a "real" value from the front-end, it would keep all the operations that would have been done on it (meaning, redo them on the new widget). Of course that would not solve the problem of printing e.g. the frequency when it doesn't exist yet (which is actually understandable), but at least it would allow to construct your audio graph as if everything already existed.

**Comment by benbovy** [comment]
> Sorry, await can't be used here since the Python interpreter has to be idle for the front-end to execute the frequency value change in the back-end.

Ah yes I was thinking about something like that but I wasn't sure.

> Something I was thinking about, what if an ipytone.Signal had a default value other than None, which would represent an "uninstanciated" Tone.Signal?

Yes that's the approach I use now more systematically in #20. "Empty" widgets (`Signal` for `frequency` and `detune`) may be created in Python and their corresponding Tone object will be assigned in JS as soon as the Tone object of their encapsulating widget (`Oscillator`) is created.

> Of course that would not solve the problem of printing e.g. the frequency when it doesn't exist yet (which is actually understandable)

I think that actually every Tone node has default options, so we can use the same defaults when constructing the corresponding widget in Python. For nodes encapsulating other nodes, initial values for sub-nodes are usually exposed as options in the main node. Regarding the actual value of, e.g., a signal that depends on other input signals, from what I see in Tone.js examples and tests we need to be within an audio running context (online or offline) to get the value at the current time or at a scheduled time anyway.

**Comment by benbovy** [comment]
Closing this. The creation of the widgets from the backend for sub-nodes seems to work well so far.
